name: Fix dependabot imports

on:
  pull_request:
    types:
      - opened
      - synchronize

permissions:
  pull-requests: write
  contents: write

jobs:
  bump-sri:
    if: github.actor == 'dependabot[bot]'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.ref }}
          repository: ${{ github.event.pull_request.head.repo.full_name }}
          submodules: true
      - uses: actions/setup-go@v4
        with:
          go-version: "1.22"
          check-latest: true
      - name: Bump Go mod
        run: ./hack/bump-go-sri
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Bump Go mod SRI
